site_name: projekt_it
nav:
  - index.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


doku doku und noch mehr doku

03.02.2023
Erstellen eines MkDocs für gemeinsame Dokumentation 