site_name: projekt_it
nav:
  - index.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


# Dokumentation

## 03.02.2023

### Erstellen eines Mkdocs für gemeinsame Dokumentation 

MKdocs haben wir mit einer Dokumentation von CT zum laufen gebracht.

Den Projektordner haben wir mit der MKDocs CLI erstellt und dann diesen in unser geteiltes Repository gepushed


## 10.02.2023

### Interview mit Herrn Burggraf zu Phasse -> Use-Case Diagramm
Neuerstellen des Diagramms, da erste Fassung zu primitiv war

nach Erstellung Verschönerungsarbeiten am Dokument durchgeführt

### Überarbeiten der MKDocs Dokumentation
Weiterführung der angefangenen Dokumentation

Anpassen und formatieren der Einträge

## 31.03.2023

### Recherche zu CAD Dateiformaten.

### einige Beispiele

#### .stl

Beschreibt Oberfläche von 3D Körpern mit Dreiecksfacetten

#### .vrml

triangulierte Oberflächen; vermeidet Redundanzen

#### .stp, .step

Standard for the Exchange of Product model data

#### .vda

Primär zum Austausch von Karasseriedaten und Gussteilen


