site_name: projekt_it
nav:
  - index.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


# Dokumentation

## 03.02.2023

### Erstellen eines Mkdocs für gemeinsame Dokumentation 

MKdocs haben wir mit einer Dokumentation von CT zum laufen gebracht.

Den Projektordner haben wir mit der MKDocs CLI erstellt und dann diesen in unser geteiltes Repository gepushed


## 10.02.2023

### Interview mit Herrn Burggraf zu Phase 1 -> Use-Case Diagramm
Neuerstellen des Diagramms, da erste Fassung nicht umfassend genug war

nach Erstellung Verschönerungsarbeiten am Diagramm durchgeführt

### Überarbeiten der MKDocs-Dokumentation
Weiterführung der angefangenen Dokumentation

Anpassen und Formatieren der Einträge

## 31.03.2023

### Recherche zu CAD-Dateiformaten.

### einige Beispiele

#### .stl

Beschreibt Oberfläche von 3D-Körpern mit Dreiecksfacetten

#### .vrml

Triangulierte Oberflächen; vermeidet Redundanzen

#### .stp, .step

Standard für Austausch von Produktmodelldaten

#### .vda

Primär zum Austausch von Karosseriedaten und Gussteilen

############################################################################

.dxf      ASCII- oder binäres Dateiformat zum Austausch von Vektordaten zwischen CAD-Programmen
		  Von Autodesk entwickelt, spielt es vorallem als Schnittstelle von und nach AutoCAD eine Rolle
		  Wird zum Digitalisieren von "Analog-Grundrissen (.PDF)" verwendet

Grundriss Allplan ArchiCAD AutoCAD nutzen .DWG

Raumplan .dwg Drawing (.PLN ArchiCAD) (AllPlan-Dateien .NDW)


Netzwerkplan .IFC (Industry Foundation Classes) nicht-proprietäre BIM-Format Sollte für den Austausch mit KD verwendet werden bei 3D Dateien

Haupt-CAD-Programm: AllPlan da am meisten Pluripotent bei den verschiedenen Dateiformaten


Nach Absprache mit Herrn Burggraf
Wir gehen davon aus, dass im AD bereits Benutzergruppen existieren und die SQL-DB mit dem AD Synchronisiert ist.
SQL befehle für den Abgleich???
-	Benutzer werden erst im AD angelegt und dann den Benutzergruppen zugeordnet


Phase 6
Notizen:
Windows Gruppenkonten verwenden
beschreiben wie die Syncronisierung funktionieren würde zwischen AllPlan und der Datenbank, wenn die Datenbank AD-Syncronisiert ist
Laut Burgraf mit libary(welche wir verwenden würden) bsp. ggf code beispielen(optional) 
Allplan NEVARIS heist die DB Schneittstelle von allplan 


Aufgabenstellung: Definieren Sie die Schnittstelle zwischen eigenen Software-Anwendungen und der gewählten Nutzerverwaltung.

Vorgehensweise: zunächst werden die Benutzer im AD (Active Diractory) angelegt. Zuvor oder danach werden benutzergruppen angelegt und die Benutzer in diese Gruppen hinzugefügt (siehe Zugriffsrechte in der Exceltabelle.
Danach melden wir uns am SQL-Server Management Studio an und erweitern die Datenbank um die von uns gewünschte Funktion der Archivierung/Verwaltung der CAD Dateien.
Dazu benutzen wir Allplan connect welches eine Schnittstelle unseres CAD Programmes ist und die Anbindung zur SQL Datenbank unterstützt. Dies erfolgt über die Allplan Connect-Einstellungen bei welcher wir den Datenbanktyp SQL auswählen müssen, um danach die Verbindung zum DB-Server in unserem lokalen Netzwerk aufbauen zu können.
Nach erfolgreicher Anmeldung auf dem DB-Server

