site_name: projekt_it
nav:
  - index.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


# Dokumentation

## 03.02.2023

### Erstellen eines Mkdocs für gemeinsame Dokumentation 

MKdocs haben wir mit einer Dokumentation von CT zum laufen gebracht.

Den Projektordner haben wir mit der MKDocs CLI erstellt und dann diesen in unser geteiltes Repository gepushed


## 10.02.2023

### Interview mit Herrn Burggraf zu Phase -> Use-Case Diagramm
Neuerstellen des Diagramms, da erste Fassung zu primitiv war

nach Erstellung Verschönerungsarbeiten am Dokument durchgeführt

### Überarbeiten der MKDocs-Dokumentation
Weiterführung der angefangenen Dokumentation

Anpassen und Formatieren der Einträge

## 31.03.2023

### Recherche zu CAD-Dateiformaten.

### einige Beispiele

#### .stl

Beschreibt Oberfläche von 3D-Körpern mit Dreiecksfacetten

#### .vrml

Triangulierte Oberflächen; vermeidet Redundanzen

#### .stp, .step

Standard for the Exchange of Product model data

#### .vda

Primär zum Austausch von Karosseriedaten und Gussteilen

############################################################################

.dxf      ASCII- oder binäres Dateiformat zum Austausch von Vektordaten zwischen CAD-Programmen
		  Von Autodesk entwickelt, spielt es vor allen Dingen als Schnittstelle von und nach AutoCAD eine Rolle
		  Ist zu verwenden beim Digitalisieren von "Analog-Grundrissen (.PDF)"

Grundriss Allplan ArchiCAD  AutoCAD nutzen .DWG

Raumplan .dwg Drawing (.PLN ArchiCAD) (AllPlan-Dateien .NDW)


Netzwerkplan .IFC Industry Foundation Classes (IFC) nicht-proprietäre BIM-Format Sollte für den Austausch mit KD verwendet werden bei 3D Dateien

Haupt-CAD-Programm: AllPlan da am meisten Pluripotent bei den verschiedenen Dateiformaten


