site_name: projekt_it
nav:
  - index.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


doku doku und noch mehr doku

03.02.2023
Erstellen eines Mkdocs für gemeinsame Dokumentation 
Wir haben die Anleitung welche aus dem Ausschnitt der CT Stammte verwendet um eine erste Dokumentation zu erstellen.
Nachdem wir den Projektordner angelegt hatten, wurde dieser via Push Befehl in unser Re

10.02.2023
Kontrolle und erweiterung unseres Uscases Diagramm (Phase 1)